---
name: Continuous Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Infrastructure"]
    types:
      - completed

jobs:
  building:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: vassilb/myapp:latest

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,quickview
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true

  deploying:
    needs: building
    name: deploy on aws-ec2 instance
    runs-on: [self-hosted]
    steps:
      - name: Pull image from docker hub
        run: docker pull vassilb/myapp:latest
      - name: Delete previous instance
        run: docker rm -f devops-final-project
      - name: Deploy latest image
        run: docker run -d -p 8080:8080 --name devops-final-project vassilb/myapp:latest
